library(dplyr)
library(ggplot2)
library(plotly)
library(rjson)

source('filenames.R')

# The plots summarizing the current status of abandoned wells in Texas are
# generated by functions in this file.

# First define variables used in generating plots.  These are defined outside
# of functions because the code in these definitions only needs to be executed
# once.

# Table giving the current distribution of abandoned wells.
abandoned_wells <- read.csv(abandoned_wells_csv_path, check.names = F,
                            stringsAsFactors = F)

# Table giving the district name and FIPS codes for each county.
counties_csv <- read.csv(counties_csv_path,
                         check.names = F,
                         colClasses = c(FIPS = 'character'),
                         stringsAsFactors = F)

# GeoJSON data used by plotly to generate a choropleth map based on FIPS codes.
counties_json <- fromJSON(file = counties_json_path)

# Find the number of missing wells per county.  In order to avoid holes in the
# choropleth map, set the county total to zero for each county not already in
# the table.  This is done by performing a full join and then setting NA to in
# the COUNTY_TOTAL column to zero.
map_data <- select(abandoned_wells, DISTRICT_NAME, COUNTY_NAME)
county_totals <- select(map_data, COUNTY_NAME) %>%
    group_by(COUNTY_NAME) %>%
    summarise(COUNTY_TOTAL = n()) %>%
    ungroup() %>%
    full_join(counties_csv, by = 'COUNTY_NAME')
bool_index <- is.na(county_totals[['COUNTY_TOTAL']])
county_totals[bool_index, 'COUNTY_TOTAL'] <- 0

# The data includes information about offshore wells that have been abandoned.
# Offshore counties were not included in the downloaded geojson data.  As a
# result, there is some missing data in the FIPS columns of the dataframe.
# For the map these rows are dropped.
county_totals <- na.omit(county_totals)

# Finte the number of missing wells per district.  Note that offshore abandoned
# wells are included in the district totals.  So on the map the sum of the
# district totals will be larger than the sum of the county totals.
district_totals <- select(map_data, DISTRICT_NAME) %>%
    group_by(DISTRICT_NAME) %>%
    summarise(DISTRICT_TOTAL = n()) %>%
    ungroup()

# Join county and district totals.
map_data <- inner_join(county_totals, district_totals, by = 'DISTRICT_NAME')


# Helper function for plotting maps.
setup_map_plot <- function(data_label) {

    if (data_label == 'Counties') {
        plot_info <- c(
            count = 'COUNTY_TOTAL',
            name = 'COUNTY_NAME',
            hovertemplate = '%{text} County<br>Total: %{z:,d}<extra></extra>',
            title = 'Abandonded wells by county'
        )
    } else {
        plot_info <- c(
            count = 'DISTRICT_TOTAL',
            name = 'DISTRICT_NAME',
            hist_title = '',
            hovertemplate = 'District %{text}<br>Total: %{z:,d}<extra></extra>',
            title = 'Abandonded wells by district'
        )
    }

    return(plot_info)
}

generate_map <- function(data_label) {

    plot_info <- setup_map_plot(data_label)

    # It seems that for choropleth maps, plotly requires the column names used
    # for the plot to be indicated as formulas, e.g., ~WELL_COUNT.  Inside the
    # current function, however, column names are stored in variables, e.g.,
    # plot_info['count'].
    #
    # The command below renames columns so that they can be referred to in
    # formulas.  Since the choice of column names to be renamed is stored in
    # variables, we need to index into the .data pronoun.  For instance, the
    # argument
    #
    # WELL_COUNT = .data[[plot_info['count']]]
    #
    # indicates that the string stored in plot_info['count'] gives the column
    # name that should be changed to 'WELL_COUNT'.
    data <- rename(map_data,
                   WELL_COUNT = .data[[plot_info['count']]],
                   NAME = .data[[plot_info['name']]])

    geo <- list(fitbounds = "locations",
                visible = F)

    hover_annotation <- list(x = 0.5, y = -0.1,
                             text = 'Hover over states to see details',
                             showarrow = F,
                             font = list(size = 16))

    colorbar_title <- 'Number of\nabandoned wells'

    fig <- plot_geo(data,
                    color = ~WELL_COUNT,
                    locationmode = 'geojson-id') %>%
        add_trace(type = 'choropleth',
                  geojson = counties_json,
                  locations = ~FIPS,
                  z = ~WELL_COUNT,
                  text = ~NAME,
                  reversescale = F,
                  colorscale = 'RdBu',
                  hovertemplate = plot_info['hovertemplate']) %>%
        colorbar(title = colorbar_title) %>%
        layout(geo = geo,
               title = plot_info['title'],
               annotations = hover_annotation) %>%
        config(displayModeBar = F, scrollZoom = F)

    return(fig)
}
