library(dplyr)
library(plotly)
library(rjson)

source('filenames.R')

# The plots summarizing the current status of abandoned wells in Texas are
# generated by functions in this file.

# First define variables used in generating plots.  These are defined outside
# of functions because the code in these definitions only needs to be executed
# once.

# Table giving the current distribution of abandoned wells.
abandoned_wells <- read.csv(abandoned_wells_csv_path, check.names = F,
                            stringsAsFactors = F)

# Table giving the district name and FIPS codes for each county.
counties_csv <- read.csv(counties_csv_path,
                         check.names = F,
                         colClasses = c(FIPS = 'character'),
                         stringsAsFactors = F)

# GeoJSON data used by plotly to generate a choropleth map based on FIPS codes.
counties_json <- fromJSON(file = counties_json_path)

# Find the number of missing wells per county.  In order to avoid holes in the
# choropleth map, set the county total to zero for each county not already in
# the table.  This is done by performing a full join and then setting NA to in
# the COUNTY_TOTAL column to zero.
wells_data <- select(abandoned_wells, DISTRICT_NAME, COUNTY_NAME)
county_totals <- select(wells_data, COUNTY_NAME) %>%
    group_by(COUNTY_NAME) %>%
    summarise(COUNTY_TOTAL = n()) %>%
    ungroup() %>%
    full_join(counties_csv, by = 'COUNTY_NAME')
bool_index <- is.na(county_totals[['COUNTY_TOTAL']])
county_totals[bool_index, 'COUNTY_TOTAL'] <- 0

# The data includes information about offshore wells that have been abandoned.
# Offshore counties were not included in the downloaded geojson data.  As a
# result, there is some missing data in the FIPS columns of the abandoned_wells
# dataframe.  For the map these rows are dropped.
county_totals <- na.omit(county_totals)

# Finte the number of missing wells per district.  Note that offshore abandoned
# wells are included in the district totals.  So on the map the sum of the
# district totals will be larger than the sum of the county totals.
district_totals <- select(wells_data, DISTRICT_NAME) %>%
    group_by(DISTRICT_NAME) %>%
    summarise(DISTRICT_TOTAL = n()) %>%
    ungroup()

# Join county and district totals.
wells_data <- inner_join(county_totals, district_totals, by = 'DISTRICT_NAME')

generate_map <- function(data_label) {

    # Set the column name to use for coloring the map.
    if (data_label == 'Counties') {
        z_column <- 'COUNTY_TOTAL'
        text_column <- 'COUNTY_NAME'
        hovertemplate <- '%{text} County<br>Total: %{z:,d}<extra></extra>'
        title <- 'Abandonded wells by county'
    } else {
        z_column <- 'DISTRICT_TOTAL'
        text_column <- 'DISTRICT_NAME'
        hovertemplate <- 'District %{text}<br>Total: %{z:,d}<extra></extra>'
        title <- 'Abandonded wells by district'
    }

    # Rename the column corresponding to data so that this column can be
    # referred to name in a formula, e.g., ~WELL_COUNT.  This seems to be
    # required by plotly.
    data <- rename(wells_data,
                   WELL_COUNT = !!z_column,
                   NAME = !!text_column)

    geo <- list(fitbounds = "locations",
                visible = F)

    hover_annotation <- list(x = 0.5, y = -0.1,
                             text = 'Hover over states to see details',
                             showarrow = F,
                             font = list(size = 16))

    colorbar_title <- 'Number of\nabandoned wells'

    fig <- plot_geo(data,
                    color = ~WELL_COUNT,
                    locationmode = 'geojson-id') %>%
        add_trace(type = 'choropleth',
                  geojson = counties_json,
                  locations = ~FIPS,
                  z = ~WELL_COUNT,
                  text = ~NAME,
                  reversescale = F,
                  colorscale = 'RdBu',
                  hovertemplate = hovertemplate) %>%
        colorbar(title = colorbar_title) %>%
        layout(geo = geo,
               title = title,
               annotations = hover_annotation) %>%
        config(displayModeBar = F, scrollZoom = F)

    return(fig)
}
